// Generated by miqt-uic. To update this file, edit the .ui file in
// Qt Designer, and then run 'go generate'.
//
//go:generate miqt-uic -InFile /home/salviati/go/src/github.com/salviati/gomics/about.ui -OutFile /home/salviati/go/src/github.com/salviati/gomics/about_ui.go -Qt6 -Package main

package main

import (
	qt "github.com/mappu/miqt/qt6"
)

type AboutDialogUi struct {
	AboutDialog    *qt.QDialog
	verticalLayout *qt.QVBoxLayout
	image          *qt.QLabel
	text           *qt.QLabel
	buttonBox      *qt.QDialogButtonBox
}

// NewAboutDialogUi creates all Qt widget classes for AboutDialog.
func NewAboutDialogUi() *AboutDialogUi {
	ui := &AboutDialogUi{}
	ui.AboutDialog = qt.NewQDialog(nil)
	AboutDialog__objectName := qt.NewQAnyStringView3("AboutDialog")
	ui.AboutDialog.SetObjectName(*AboutDialog__objectName)
	AboutDialog__objectName.Delete() // setter copied value
	ui.AboutDialog.SetWindowModality(qt.ApplicationModal)
	ui.AboutDialog.Resize(492, 321)
	AboutDialog__sizePolicy := qt.NewQSizePolicy()
	AboutDialog__sizePolicy.SetHorizontalPolicy(qt.QSizePolicy__Fixed)
	AboutDialog__sizePolicy.SetVerticalPolicy(qt.QSizePolicy__Fixed)
	AboutDialog__sizePolicy.SetHorizontalStretch(0)
	AboutDialog__sizePolicy.SetVerticalStretch(0)
	AboutDialog__sizePolicy.SetHeightForWidth(ui.AboutDialog.SizePolicy().HasHeightForWidth())
	ui.AboutDialog.SetSizePolicy(*AboutDialog__sizePolicy)
	AboutDialog__sizePolicy.Delete() // setter copies values
	ui.verticalLayout = qt.NewQVBoxLayout(ui.AboutDialog.QWidget)
	verticalLayout__objectName := qt.NewQAnyStringView3("verticalLayout")
	ui.verticalLayout.SetObjectName(*verticalLayout__objectName)
	verticalLayout__objectName.Delete() // setter copied value
	ui.verticalLayout.SetSizeConstraint(qt.QLayout__SetFixedSize)
	ui.verticalLayout.SetContentsMargins(11, 11, 11, 11)
	ui.verticalLayout.SetSpacing(6)
	ui.image = qt.NewQLabel(ui.AboutDialog.QWidget)
	image__objectName := qt.NewQAnyStringView3("image")
	ui.image.SetObjectName(*image__objectName)
	image__objectName.Delete() // setter copied value
	/* miqt-uic: no handler for image property 'pixmap' */

	ui.verticalLayout.AddWidget(ui.image.QWidget)
	ui.text = qt.NewQLabel(ui.AboutDialog.QWidget)
	text__objectName := qt.NewQAnyStringView3("text")
	ui.text.SetObjectName(*text__objectName)
	text__objectName.Delete() // setter copied value
	text__sizePolicy := qt.NewQSizePolicy()
	text__sizePolicy.SetHorizontalPolicy(qt.QSizePolicy__MinimumExpanding)
	text__sizePolicy.SetVerticalPolicy(qt.QSizePolicy__MinimumExpanding)
	text__sizePolicy.SetHorizontalStretch(0)
	text__sizePolicy.SetVerticalStretch(0)
	text__sizePolicy.SetHeightForWidth(ui.text.SizePolicy().HasHeightForWidth())
	ui.text.SetSizePolicy(*text__sizePolicy)
	text__sizePolicy.Delete() // setter copies values
	ui.text.SetAlignment(qt.AlignHCenter | qt.AlignTop)
	ui.text.SetWordWrap(true)

	ui.verticalLayout.AddWidget(ui.text.QWidget)
	ui.buttonBox = qt.NewQDialogButtonBox(ui.AboutDialog.QWidget)
	buttonBox__objectName := qt.NewQAnyStringView3("buttonBox")
	ui.buttonBox.SetObjectName(*buttonBox__objectName)
	buttonBox__objectName.Delete() // setter copied value
	ui.buttonBox.SetOrientation(qt.Horizontal)
	ui.buttonBox.SetStandardButtons(qt.QDialogButtonBox__Ok)
	ui.buttonBox.SetCenterButtons(true)

	ui.verticalLayout.AddWidget(ui.buttonBox.QWidget)

	ui.buttonBox.OnAccepted(ui.AboutDialog.Accept)
	ui.buttonBox.OnRejected(ui.AboutDialog.Reject)

	ui.Retranslate()

	return ui
}

// Retranslate reapplies all text translations.
func (ui *AboutDialogUi) Retranslate() {
	ui.AboutDialog.SetWindowTitle(qt.QCoreApplication_Tr("About"))
	ui.image.SetText(qt.QDialog_Tr(""))
	ui.text.SetText(qt.QDialog_Tr("Gomics is a fast and resource efficient image viewer for comic archives written in Go, freely available under GPL v3."))
}
