// Generated by miqt-uic. To update this file, edit the .ui file in
// Qt Designer, and then run 'go generate'.
//
//go:generate miqt-uic -InFile /home/salviati/go/src/github.com/salviati/gomics/goto.ui -OutFile /home/salviati/go/src/github.com/salviati/gomics/goto_ui.go -Qt6 -Package main

package main

import (
	qt "github.com/mappu/miqt/qt6"
)

type GoToDialogUi struct {
	Dialog             *qt.QDialog
	verticalLayout     *qt.QVBoxLayout
	horizontalLayout   *qt.QHBoxLayout
	GoToSpinButton     *qt.QSpinBox
	GoToScrollbar      *qt.QScrollBar
	GoToThumbnailImage *qt.QGraphicsView
	buttonBox          *qt.QDialogButtonBox
}

// NewGoToDialogUi creates all Qt widget classes for GoToDialog.
func NewGoToDialogUi() *GoToDialogUi {
	ui := &GoToDialogUi{}
	ui.Dialog = qt.NewQDialog(nil)
	Dialog__objectName := qt.NewQAnyStringView3("Dialog")
	ui.Dialog.SetObjectName(*Dialog__objectName)
	Dialog__objectName.Delete() // setter copied value
	ui.Dialog.Resize(400, 300)
	ui.verticalLayout = qt.NewQVBoxLayout(ui.Dialog.QWidget)
	verticalLayout__objectName := qt.NewQAnyStringView3("verticalLayout")
	ui.verticalLayout.SetObjectName(*verticalLayout__objectName)
	verticalLayout__objectName.Delete() // setter copied value
	ui.verticalLayout.SetContentsMargins(11, 11, 11, 11)
	ui.verticalLayout.SetSpacing(6)
	ui.horizontalLayout = qt.NewQHBoxLayout2()
	horizontalLayout__objectName := qt.NewQAnyStringView3("horizontalLayout")
	ui.horizontalLayout.SetObjectName(*horizontalLayout__objectName)
	horizontalLayout__objectName.Delete() // setter copied value
	ui.horizontalLayout.SetContentsMargins(0, 0, 0, 0)
	ui.horizontalLayout.SetSpacing(6)
	ui.GoToSpinButton = qt.NewQSpinBox(ui.Dialog.QWidget)
	GoToSpinButton__objectName := qt.NewQAnyStringView3("GoToSpinButton")
	ui.GoToSpinButton.SetObjectName(*GoToSpinButton__objectName)
	GoToSpinButton__objectName.Delete() // setter copied value
	GoToSpinButton__sizePolicy := qt.NewQSizePolicy()
	GoToSpinButton__sizePolicy.SetHorizontalPolicy(qt.QSizePolicy__Fixed)
	GoToSpinButton__sizePolicy.SetVerticalPolicy(qt.QSizePolicy__Fixed)
	GoToSpinButton__sizePolicy.SetHorizontalStretch(0)
	GoToSpinButton__sizePolicy.SetVerticalStretch(0)
	GoToSpinButton__sizePolicy.SetHeightForWidth(ui.GoToSpinButton.SizePolicy().HasHeightForWidth())
	ui.GoToSpinButton.SetSizePolicy(*GoToSpinButton__sizePolicy)
	GoToSpinButton__sizePolicy.Delete() // setter copies values

	ui.horizontalLayout.AddWidget(ui.GoToSpinButton.QWidget)
	ui.GoToScrollbar = qt.NewQScrollBar(ui.Dialog.QWidget)
	GoToScrollbar__objectName := qt.NewQAnyStringView3("GoToScrollbar")
	ui.GoToScrollbar.SetObjectName(*GoToScrollbar__objectName)
	GoToScrollbar__objectName.Delete() // setter copied value
	ui.GoToScrollbar.SetOrientation(qt.Horizontal)

	ui.horizontalLayout.AddWidget(ui.GoToScrollbar.QWidget)

	ui.verticalLayout.AddLayout(ui.horizontalLayout.QLayout)
	ui.GoToThumbnailImage = qt.NewQGraphicsView(ui.Dialog.QWidget)
	GoToThumbnailImage__objectName := qt.NewQAnyStringView3("GoToThumbnailImage")
	ui.GoToThumbnailImage.SetObjectName(*GoToThumbnailImage__objectName)
	GoToThumbnailImage__objectName.Delete() // setter copied value

	ui.verticalLayout.AddWidget(ui.GoToThumbnailImage.QWidget)
	ui.buttonBox = qt.NewQDialogButtonBox(ui.Dialog.QWidget)
	buttonBox__objectName := qt.NewQAnyStringView3("buttonBox")
	ui.buttonBox.SetObjectName(*buttonBox__objectName)
	buttonBox__objectName.Delete() // setter copied value
	ui.buttonBox.SetOrientation(qt.Horizontal)
	ui.buttonBox.SetStandardButtons(qt.QDialogButtonBox__Cancel | qt.QDialogButtonBox__Ok)

	ui.verticalLayout.AddWidget(ui.buttonBox.QWidget)

	ui.buttonBox.OnAccepted(ui.Dialog.Accept)
	ui.buttonBox.OnRejected(ui.Dialog.Reject)

	ui.Retranslate()

	return ui
}

// Retranslate reapplies all text translations.
func (ui *GoToDialogUi) Retranslate() {
	ui.Dialog.SetWindowTitle(qt.QCoreApplication_Tr("Go to.."))
}
