// Generated by miqt-uic. To update this file, edit the .ui file in
// Qt Designer, and then run 'go generate'.
//
//go:generate miqt-uic -InFile /home/salviati/go/src/github.com/salviati/gomics/mainwindow.ui -OutFile /home/salviati/go/src/github.com/salviati/gomics/mainwindow_ui.go -Qt6 -Package main

package main

import (
	qt "github.com/mappu/miqt/qt6"
)

type MainWindowUi struct {
	MainWindow                 *qt.QMainWindow
	centralwidget              *qt.QWidget
	verticalLayout             *qt.QVBoxLayout
	Image                      *qt.QGraphicsView
	menubar                    *qt.QMenuBar
	menuFile                   *qt.QMenu
	menu_Recent_Files          *qt.QMenu
	menu_Edit                  *qt.QMenu
	menu_View                  *qt.QMenu
	menu_Zoom                  *qt.QMenu
	menu_Rotate                *qt.QMenu
	menuNavigation             *qt.QMenu
	menuBookmarks              *qt.QMenu
	menuHelp                   *qt.QMenu
	statusbar                  *qt.QStatusBar
	toolBar                    *qt.QToolBar
	actionOpen                 *qt.QAction
	action_no_recent_items     *qt.QAction
	actionClose                *qt.QAction
	actionSave_Image           *qt.QAction
	action_Quit                *qt.QAction
	action_Preferences         *qt.QAction
	actionShrink_large_images  *qt.QAction
	actionEnlarge_small_images *qt.QAction
	actionBest_fit             *qt.QAction
	actionZoom_25              *qt.QAction
	actionZoom_33              *qt.QAction
	actionZoom_50              *qt.QAction
	actionZoom_66              *qt.QAction
	actionZoom_75              *qt.QAction
	actionZoom_100             *qt.QAction
	actionZoom_125             *qt.QAction
	actionZoom_150             *qt.QAction
	actionZoom_200             *qt.QAction
	actionZoom_300             *qt.QAction
	actionZoom_400             *qt.QAction
	actionZoom_800             *qt.QAction
	actionRotate_0             *qt.QAction
	actionRotate_90            *qt.QAction
	actionRotate_180           *qt.QAction
	actionRotate_270           *qt.QAction
	actionFit_to_width         *qt.QAction
	actionFit_to_height        *qt.QAction
	actionFullscreen           *qt.QAction
	actionSeamless_mode        *qt.QAction
	actionRandom_ordering      *qt.QAction
	actionV_flip               *qt.QAction
	actionH_flip               *qt.QAction
	actionManga_mode           *qt.QAction
	actionDouble_page          *qt.QAction
	actionPrevious_page        *qt.QAction
	actionNext_page            *qt.QAction
	actionSkip_forward         *qt.QAction
	actionSkip_backward        *qt.QAction
	actionFirst_page           *qt.QAction
	actionLast_page            *qt.QAction
	actionPrevious_archive     *qt.QAction
	actionNext_archive         *qt.QAction
	actionGo_to_page           *qt.QAction
	actionAdd_bookmark         *qt.QAction
	actionAbout                *qt.QAction
	actionPrevious_Scene       *qt.QAction
	actionNext_scene           *qt.QAction
}

// NewMainWindowUi creates all Qt widget classes for MainWindow.
func NewMainWindowUi() *MainWindowUi {
	ui := &MainWindowUi{}
	ui.MainWindow = qt.NewQMainWindow(nil)
	MainWindow__objectName := qt.NewQAnyStringView3("MainWindow")
	ui.MainWindow.SetObjectName(*MainWindow__objectName)
	MainWindow__objectName.Delete() // setter copied value
	ui.MainWindow.Resize(1055, 741)
	ui.actionOpen = qt.NewQAction()
	actionOpen__objectName := qt.NewQAnyStringView3("actionOpen")
	ui.actionOpen.SetObjectName(*actionOpen__objectName)
	actionOpen__objectName.Delete() // setter copied value
	icon0 := qt.QIcon_FromTheme("document-open")
	ui.actionOpen.SetIcon(icon0)
	ui.action_no_recent_items = qt.NewQAction()
	action_no_recent_items__objectName := qt.NewQAnyStringView3("action_no_recent_items")
	ui.action_no_recent_items.SetObjectName(*action_no_recent_items__objectName)
	action_no_recent_items__objectName.Delete() // setter copied value
	ui.actionClose = qt.NewQAction()
	actionClose__objectName := qt.NewQAnyStringView3("actionClose")
	ui.actionClose.SetObjectName(*actionClose__objectName)
	actionClose__objectName.Delete() // setter copied value
	icon1 := qt.QIcon_FromTheme("window-close")
	ui.actionClose.SetIcon(icon1)
	ui.actionSave_Image = qt.NewQAction()
	actionSave_Image__objectName := qt.NewQAnyStringView3("actionSave_Image")
	ui.actionSave_Image.SetObjectName(*actionSave_Image__objectName)
	actionSave_Image__objectName.Delete() // setter copied value
	icon2 := qt.QIcon_FromTheme("document-save")
	ui.actionSave_Image.SetIcon(icon2)
	ui.action_Quit = qt.NewQAction()
	action_Quit__objectName := qt.NewQAnyStringView3("action_Quit")
	ui.action_Quit.SetObjectName(*action_Quit__objectName)
	action_Quit__objectName.Delete() // setter copied value
	icon3 := qt.QIcon_FromTheme("window-close")
	ui.action_Quit.SetIcon(icon3)
	ui.action_Preferences = qt.NewQAction()
	action_Preferences__objectName := qt.NewQAnyStringView3("action_Preferences")
	ui.action_Preferences.SetObjectName(*action_Preferences__objectName)
	action_Preferences__objectName.Delete() // setter copied value
	ui.actionShrink_large_images = qt.NewQAction()
	actionShrink_large_images__objectName := qt.NewQAnyStringView3("actionShrink_large_images")
	ui.actionShrink_large_images.SetObjectName(*actionShrink_large_images__objectName)
	actionShrink_large_images__objectName.Delete() // setter copied value
	/* miqt-uic: no handler for QAction property 'checkable' */
	ui.actionEnlarge_small_images = qt.NewQAction()
	actionEnlarge_small_images__objectName := qt.NewQAnyStringView3("actionEnlarge_small_images")
	ui.actionEnlarge_small_images.SetObjectName(*actionEnlarge_small_images__objectName)
	actionEnlarge_small_images__objectName.Delete() // setter copied value
	/* miqt-uic: no handler for QAction property 'checkable' */
	ui.actionBest_fit = qt.NewQAction()
	actionBest_fit__objectName := qt.NewQAnyStringView3("actionBest_fit")
	ui.actionBest_fit.SetObjectName(*actionBest_fit__objectName)
	actionBest_fit__objectName.Delete() // setter copied value
	/* miqt-uic: no handler for QAction property 'checkable' */
	icon4 := qt.QIcon_FromTheme("zoom-fit-best")
	ui.actionBest_fit.SetIcon(icon4)
	ui.actionZoom_25 = qt.NewQAction()
	actionZoom_25__objectName := qt.NewQAnyStringView3("actionZoom_25")
	ui.actionZoom_25.SetObjectName(*actionZoom_25__objectName)
	actionZoom_25__objectName.Delete() // setter copied value
	/* miqt-uic: no handler for QAction property 'checkable' */
	ui.actionZoom_33 = qt.NewQAction()
	actionZoom_33__objectName := qt.NewQAnyStringView3("actionZoom_33")
	ui.actionZoom_33.SetObjectName(*actionZoom_33__objectName)
	actionZoom_33__objectName.Delete() // setter copied value
	/* miqt-uic: no handler for QAction property 'checkable' */
	ui.actionZoom_50 = qt.NewQAction()
	actionZoom_50__objectName := qt.NewQAnyStringView3("actionZoom_50")
	ui.actionZoom_50.SetObjectName(*actionZoom_50__objectName)
	actionZoom_50__objectName.Delete() // setter copied value
	/* miqt-uic: no handler for QAction property 'checkable' */
	ui.actionZoom_66 = qt.NewQAction()
	actionZoom_66__objectName := qt.NewQAnyStringView3("actionZoom_66")
	ui.actionZoom_66.SetObjectName(*actionZoom_66__objectName)
	actionZoom_66__objectName.Delete() // setter copied value
	/* miqt-uic: no handler for QAction property 'checkable' */
	ui.actionZoom_75 = qt.NewQAction()
	actionZoom_75__objectName := qt.NewQAnyStringView3("actionZoom_75")
	ui.actionZoom_75.SetObjectName(*actionZoom_75__objectName)
	actionZoom_75__objectName.Delete() // setter copied value
	/* miqt-uic: no handler for QAction property 'checkable' */
	ui.actionZoom_100 = qt.NewQAction()
	actionZoom_100__objectName := qt.NewQAnyStringView3("actionZoom_100")
	ui.actionZoom_100.SetObjectName(*actionZoom_100__objectName)
	actionZoom_100__objectName.Delete() // setter copied value
	/* miqt-uic: no handler for QAction property 'checkable' */
	ui.actionZoom_125 = qt.NewQAction()
	actionZoom_125__objectName := qt.NewQAnyStringView3("actionZoom_125")
	ui.actionZoom_125.SetObjectName(*actionZoom_125__objectName)
	actionZoom_125__objectName.Delete() // setter copied value
	/* miqt-uic: no handler for QAction property 'checkable' */
	ui.actionZoom_150 = qt.NewQAction()
	actionZoom_150__objectName := qt.NewQAnyStringView3("actionZoom_150")
	ui.actionZoom_150.SetObjectName(*actionZoom_150__objectName)
	actionZoom_150__objectName.Delete() // setter copied value
	/* miqt-uic: no handler for QAction property 'checkable' */
	ui.actionZoom_200 = qt.NewQAction()
	actionZoom_200__objectName := qt.NewQAnyStringView3("actionZoom_200")
	ui.actionZoom_200.SetObjectName(*actionZoom_200__objectName)
	actionZoom_200__objectName.Delete() // setter copied value
	/* miqt-uic: no handler for QAction property 'checkable' */
	ui.actionZoom_300 = qt.NewQAction()
	actionZoom_300__objectName := qt.NewQAnyStringView3("actionZoom_300")
	ui.actionZoom_300.SetObjectName(*actionZoom_300__objectName)
	actionZoom_300__objectName.Delete() // setter copied value
	/* miqt-uic: no handler for QAction property 'checkable' */
	ui.actionZoom_400 = qt.NewQAction()
	actionZoom_400__objectName := qt.NewQAnyStringView3("actionZoom_400")
	ui.actionZoom_400.SetObjectName(*actionZoom_400__objectName)
	actionZoom_400__objectName.Delete() // setter copied value
	/* miqt-uic: no handler for QAction property 'checkable' */
	ui.actionZoom_800 = qt.NewQAction()
	actionZoom_800__objectName := qt.NewQAnyStringView3("actionZoom_800")
	ui.actionZoom_800.SetObjectName(*actionZoom_800__objectName)
	actionZoom_800__objectName.Delete() // setter copied value
	/* miqt-uic: no handler for QAction property 'checkable' */
	ui.actionRotate_0 = qt.NewQAction()
	actionRotate_0__objectName := qt.NewQAnyStringView3("actionRotate_0")
	ui.actionRotate_0.SetObjectName(*actionRotate_0__objectName)
	actionRotate_0__objectName.Delete() // setter copied value
	/* miqt-uic: no handler for QAction property 'checkable' */
	ui.actionRotate_90 = qt.NewQAction()
	actionRotate_90__objectName := qt.NewQAnyStringView3("actionRotate_90")
	ui.actionRotate_90.SetObjectName(*actionRotate_90__objectName)
	actionRotate_90__objectName.Delete() // setter copied value
	/* miqt-uic: no handler for QAction property 'checkable' */
	ui.actionRotate_180 = qt.NewQAction()
	actionRotate_180__objectName := qt.NewQAnyStringView3("actionRotate_180")
	ui.actionRotate_180.SetObjectName(*actionRotate_180__objectName)
	actionRotate_180__objectName.Delete() // setter copied value
	/* miqt-uic: no handler for QAction property 'checkable' */
	ui.actionRotate_270 = qt.NewQAction()
	actionRotate_270__objectName := qt.NewQAnyStringView3("actionRotate_270")
	ui.actionRotate_270.SetObjectName(*actionRotate_270__objectName)
	actionRotate_270__objectName.Delete() // setter copied value
	/* miqt-uic: no handler for QAction property 'checkable' */
	ui.actionFit_to_width = qt.NewQAction()
	actionFit_to_width__objectName := qt.NewQAnyStringView3("actionFit_to_width")
	ui.actionFit_to_width.SetObjectName(*actionFit_to_width__objectName)
	actionFit_to_width__objectName.Delete() // setter copied value
	/* miqt-uic: no handler for QAction property 'checkable' */
	ui.actionFit_to_height = qt.NewQAction()
	actionFit_to_height__objectName := qt.NewQAnyStringView3("actionFit_to_height")
	ui.actionFit_to_height.SetObjectName(*actionFit_to_height__objectName)
	actionFit_to_height__objectName.Delete() // setter copied value
	/* miqt-uic: no handler for QAction property 'checkable' */
	ui.actionFullscreen = qt.NewQAction()
	actionFullscreen__objectName := qt.NewQAnyStringView3("actionFullscreen")
	ui.actionFullscreen.SetObjectName(*actionFullscreen__objectName)
	actionFullscreen__objectName.Delete() // setter copied value
	icon5 := qt.QIcon_FromTheme("view-fullscreen")
	ui.actionFullscreen.SetIcon(icon5)
	ui.actionSeamless_mode = qt.NewQAction()
	actionSeamless_mode__objectName := qt.NewQAnyStringView3("actionSeamless_mode")
	ui.actionSeamless_mode.SetObjectName(*actionSeamless_mode__objectName)
	actionSeamless_mode__objectName.Delete() // setter copied value
	ui.actionRandom_ordering = qt.NewQAction()
	actionRandom_ordering__objectName := qt.NewQAnyStringView3("actionRandom_ordering")
	ui.actionRandom_ordering.SetObjectName(*actionRandom_ordering__objectName)
	actionRandom_ordering__objectName.Delete() // setter copied value
	ui.actionV_flip = qt.NewQAction()
	actionV_flip__objectName := qt.NewQAnyStringView3("actionV_flip")
	ui.actionV_flip.SetObjectName(*actionV_flip__objectName)
	actionV_flip__objectName.Delete() // setter copied value
	icon6 := qt.QIcon_FromTheme("object-flip-vertical")
	ui.actionV_flip.SetIcon(icon6)
	ui.actionH_flip = qt.NewQAction()
	actionH_flip__objectName := qt.NewQAnyStringView3("actionH_flip")
	ui.actionH_flip.SetObjectName(*actionH_flip__objectName)
	actionH_flip__objectName.Delete() // setter copied value
	icon7 := qt.QIcon_FromTheme("object-flip-horizontal")
	ui.actionH_flip.SetIcon(icon7)
	ui.actionManga_mode = qt.NewQAction()
	actionManga_mode__objectName := qt.NewQAnyStringView3("actionManga_mode")
	ui.actionManga_mode.SetObjectName(*actionManga_mode__objectName)
	actionManga_mode__objectName.Delete() // setter copied value
	ui.actionDouble_page = qt.NewQAction()
	actionDouble_page__objectName := qt.NewQAnyStringView3("actionDouble_page")
	ui.actionDouble_page.SetObjectName(*actionDouble_page__objectName)
	actionDouble_page__objectName.Delete() // setter copied value
	ui.actionPrevious_page = qt.NewQAction()
	actionPrevious_page__objectName := qt.NewQAnyStringView3("actionPrevious_page")
	ui.actionPrevious_page.SetObjectName(*actionPrevious_page__objectName)
	actionPrevious_page__objectName.Delete() // setter copied value
	icon8 := qt.QIcon_FromTheme("go-previous")
	ui.actionPrevious_page.SetIcon(icon8)
	ui.actionNext_page = qt.NewQAction()
	actionNext_page__objectName := qt.NewQAnyStringView3("actionNext_page")
	ui.actionNext_page.SetObjectName(*actionNext_page__objectName)
	actionNext_page__objectName.Delete() // setter copied value
	icon9 := qt.QIcon_FromTheme("go-next")
	ui.actionNext_page.SetIcon(icon9)
	ui.actionSkip_forward = qt.NewQAction()
	actionSkip_forward__objectName := qt.NewQAnyStringView3("actionSkip_forward")
	ui.actionSkip_forward.SetObjectName(*actionSkip_forward__objectName)
	actionSkip_forward__objectName.Delete() // setter copied value
	icon10 := qt.QIcon_FromTheme("media-seek-forward")
	ui.actionSkip_forward.SetIcon(icon10)
	ui.actionSkip_backward = qt.NewQAction()
	actionSkip_backward__objectName := qt.NewQAnyStringView3("actionSkip_backward")
	ui.actionSkip_backward.SetObjectName(*actionSkip_backward__objectName)
	actionSkip_backward__objectName.Delete() // setter copied value
	icon11 := qt.QIcon_FromTheme("media-seek-backward")
	ui.actionSkip_backward.SetIcon(icon11)
	ui.actionFirst_page = qt.NewQAction()
	actionFirst_page__objectName := qt.NewQAnyStringView3("actionFirst_page")
	ui.actionFirst_page.SetObjectName(*actionFirst_page__objectName)
	actionFirst_page__objectName.Delete() // setter copied value
	icon12 := qt.QIcon_FromTheme("media-skip-backward")
	ui.actionFirst_page.SetIcon(icon12)
	ui.actionLast_page = qt.NewQAction()
	actionLast_page__objectName := qt.NewQAnyStringView3("actionLast_page")
	ui.actionLast_page.SetObjectName(*actionLast_page__objectName)
	actionLast_page__objectName.Delete() // setter copied value
	icon13 := qt.QIcon_FromTheme("media-skip-forward")
	ui.actionLast_page.SetIcon(icon13)
	ui.actionPrevious_archive = qt.NewQAction()
	actionPrevious_archive__objectName := qt.NewQAnyStringView3("actionPrevious_archive")
	ui.actionPrevious_archive.SetObjectName(*actionPrevious_archive__objectName)
	actionPrevious_archive__objectName.Delete() // setter copied value
	icon14 := qt.QIcon_FromTheme("go-previous")
	ui.actionPrevious_archive.SetIcon(icon14)
	ui.actionNext_archive = qt.NewQAction()
	actionNext_archive__objectName := qt.NewQAnyStringView3("actionNext_archive")
	ui.actionNext_archive.SetObjectName(*actionNext_archive__objectName)
	actionNext_archive__objectName.Delete() // setter copied value
	icon15 := qt.QIcon_FromTheme("go-next")
	ui.actionNext_archive.SetIcon(icon15)
	ui.actionGo_to_page = qt.NewQAction()
	actionGo_to_page__objectName := qt.NewQAnyStringView3("actionGo_to_page")
	ui.actionGo_to_page.SetObjectName(*actionGo_to_page__objectName)
	actionGo_to_page__objectName.Delete() // setter copied value
	ui.actionAdd_bookmark = qt.NewQAction()
	actionAdd_bookmark__objectName := qt.NewQAnyStringView3("actionAdd_bookmark")
	ui.actionAdd_bookmark.SetObjectName(*actionAdd_bookmark__objectName)
	actionAdd_bookmark__objectName.Delete() // setter copied value
	ui.actionAbout = qt.NewQAction()
	actionAbout__objectName := qt.NewQAnyStringView3("actionAbout")
	ui.actionAbout.SetObjectName(*actionAbout__objectName)
	actionAbout__objectName.Delete() // setter copied value
	icon16 := qt.QIcon_FromTheme("help-about")
	ui.actionAbout.SetIcon(icon16)
	ui.actionPrevious_Scene = qt.NewQAction()
	actionPrevious_Scene__objectName := qt.NewQAnyStringView3("actionPrevious_Scene")
	ui.actionPrevious_Scene.SetObjectName(*actionPrevious_Scene__objectName)
	actionPrevious_Scene__objectName.Delete() // setter copied value
	icon17 := qt.QIcon_FromTheme("go-previous")
	ui.actionPrevious_Scene.SetIcon(icon17)
	/* miqt-uic: no handler for QAction property 'menuRole' */
	ui.actionNext_scene = qt.NewQAction()
	actionNext_scene__objectName := qt.NewQAnyStringView3("actionNext_scene")
	ui.actionNext_scene.SetObjectName(*actionNext_scene__objectName)
	actionNext_scene__objectName.Delete() // setter copied value
	icon18 := qt.QIcon_FromTheme("go-next")
	ui.actionNext_scene.SetIcon(icon18)
	/* miqt-uic: no handler for QAction property 'menuRole' */
	ui.centralwidget = qt.NewQWidget(ui.MainWindow.QWidget)
	centralwidget__objectName := qt.NewQAnyStringView3("centralwidget")
	ui.centralwidget.SetObjectName(*centralwidget__objectName)
	centralwidget__objectName.Delete() // setter copied value
	ui.verticalLayout = qt.NewQVBoxLayout(ui.centralwidget)
	verticalLayout__objectName := qt.NewQAnyStringView3("verticalLayout")
	ui.verticalLayout.SetObjectName(*verticalLayout__objectName)
	verticalLayout__objectName.Delete() // setter copied value
	ui.verticalLayout.SetContentsMargins(11, 11, 11, 11)
	ui.verticalLayout.SetSpacing(6)
	ui.Image = qt.NewQGraphicsView(ui.centralwidget)
	Image__objectName := qt.NewQAnyStringView3("Image")
	ui.Image.SetObjectName(*Image__objectName)
	Image__objectName.Delete() // setter copied value

	ui.verticalLayout.AddWidget(ui.Image.QWidget)
	ui.MainWindow.SetCentralWidget(ui.centralwidget) // Set central widget
	ui.menubar = qt.NewQMenuBar(ui.MainWindow.QWidget)
	menubar__objectName := qt.NewQAnyStringView3("menubar")
	ui.menubar.SetObjectName(*menubar__objectName)
	menubar__objectName.Delete() // setter copied value
	ui.menubar.Resize(1055, 30)
	ui.menuFile = qt.NewQMenu(ui.menubar.QWidget)
	menuFile__objectName := qt.NewQAnyStringView3("menuFile")
	ui.menuFile.SetObjectName(*menuFile__objectName)
	menuFile__objectName.Delete() // setter copied value
	ui.menu_Recent_Files = qt.NewQMenu(ui.menuFile.QWidget)
	menu_Recent_Files__objectName := qt.NewQAnyStringView3("menu_Recent_Files")
	ui.menu_Recent_Files.SetObjectName(*menu_Recent_Files__objectName)
	menu_Recent_Files__objectName.Delete() // setter copied value
	ui.menu_Recent_Files.QWidget.AddAction(ui.action_no_recent_items)
	ui.menuFile.QWidget.AddAction(ui.actionOpen)
	ui.menuFile.AddMenu(ui.menu_Recent_Files)
	ui.menuFile.QWidget.AddAction(ui.actionClose)
	ui.menuFile.QWidget.AddAction(ui.actionSave_Image)
	ui.menuFile.AddSeparator()
	ui.menuFile.QWidget.AddAction(ui.action_Quit)
	ui.menu_Edit = qt.NewQMenu(ui.menubar.QWidget)
	menu_Edit__objectName := qt.NewQAnyStringView3("menu_Edit")
	ui.menu_Edit.SetObjectName(*menu_Edit__objectName)
	menu_Edit__objectName.Delete() // setter copied value
	ui.menu_Edit.QWidget.AddAction(ui.action_Preferences)
	ui.menu_View = qt.NewQMenu(ui.menubar.QWidget)
	menu_View__objectName := qt.NewQAnyStringView3("menu_View")
	ui.menu_View.SetObjectName(*menu_View__objectName)
	menu_View__objectName.Delete() // setter copied value
	ui.menu_Zoom = qt.NewQMenu(ui.menu_View.QWidget)
	menu_Zoom__objectName := qt.NewQAnyStringView3("menu_Zoom")
	ui.menu_Zoom.SetObjectName(*menu_Zoom__objectName)
	menu_Zoom__objectName.Delete() // setter copied value
	ui.menu_Zoom.QWidget.AddAction(ui.actionZoom_25)
	ui.menu_Zoom.QWidget.AddAction(ui.actionZoom_33)
	ui.menu_Zoom.QWidget.AddAction(ui.actionZoom_50)
	ui.menu_Zoom.QWidget.AddAction(ui.actionZoom_66)
	ui.menu_Zoom.QWidget.AddAction(ui.actionZoom_75)
	ui.menu_Zoom.QWidget.AddAction(ui.actionZoom_100)
	ui.menu_Zoom.QWidget.AddAction(ui.actionZoom_125)
	ui.menu_Zoom.QWidget.AddAction(ui.actionZoom_150)
	ui.menu_Zoom.QWidget.AddAction(ui.actionZoom_200)
	ui.menu_Zoom.QWidget.AddAction(ui.actionZoom_300)
	ui.menu_Zoom.QWidget.AddAction(ui.actionZoom_400)
	ui.menu_Zoom.QWidget.AddAction(ui.actionZoom_800)
	ui.menu_Rotate = qt.NewQMenu(ui.menu_View.QWidget)
	menu_Rotate__objectName := qt.NewQAnyStringView3("menu_Rotate")
	ui.menu_Rotate.SetObjectName(*menu_Rotate__objectName)
	menu_Rotate__objectName.Delete() // setter copied value
	ui.menu_Rotate.QWidget.AddAction(ui.actionRotate_0)
	ui.menu_Rotate.QWidget.AddAction(ui.actionRotate_90)
	ui.menu_Rotate.QWidget.AddAction(ui.actionRotate_180)
	ui.menu_Rotate.QWidget.AddAction(ui.actionRotate_270)
	ui.menu_View.QWidget.AddAction(ui.actionShrink_large_images)
	ui.menu_View.QWidget.AddAction(ui.actionEnlarge_small_images)
	ui.menu_View.AddSeparator()
	ui.menu_View.QWidget.AddAction(ui.actionBest_fit)
	ui.menu_View.AddMenu(ui.menu_Zoom)
	ui.menu_View.QWidget.AddAction(ui.actionFit_to_width)
	ui.menu_View.QWidget.AddAction(ui.actionFit_to_height)
	ui.menu_View.AddSeparator()
	ui.menu_View.QWidget.AddAction(ui.actionFullscreen)
	ui.menu_View.QWidget.AddAction(ui.actionSeamless_mode)
	ui.menu_View.QWidget.AddAction(ui.actionRandom_ordering)
	ui.menu_View.AddSeparator()
	ui.menu_View.QWidget.AddAction(ui.actionV_flip)
	ui.menu_View.QWidget.AddAction(ui.actionH_flip)
	ui.menu_View.QWidget.AddAction(ui.actionManga_mode)
	ui.menu_View.QWidget.AddAction(ui.actionDouble_page)
	ui.menu_View.AddMenu(ui.menu_Rotate)
	ui.menuNavigation = qt.NewQMenu(ui.menubar.QWidget)
	menuNavigation__objectName := qt.NewQAnyStringView3("menuNavigation")
	ui.menuNavigation.SetObjectName(*menuNavigation__objectName)
	menuNavigation__objectName.Delete() // setter copied value
	ui.menuNavigation.QWidget.AddAction(ui.actionPrevious_page)
	ui.menuNavigation.QWidget.AddAction(ui.actionNext_page)
	ui.menuNavigation.AddSeparator()
	ui.menuNavigation.QWidget.AddAction(ui.actionSkip_forward)
	ui.menuNavigation.QWidget.AddAction(ui.actionSkip_backward)
	ui.menuNavigation.AddSeparator()
	ui.menuNavigation.QWidget.AddAction(ui.actionFirst_page)
	ui.menuNavigation.QWidget.AddAction(ui.actionLast_page)
	ui.menuNavigation.AddSeparator()
	ui.menuNavigation.QWidget.AddAction(ui.actionPrevious_archive)
	ui.menuNavigation.QWidget.AddAction(ui.actionNext_archive)
	ui.menuNavigation.AddSeparator()
	ui.menuNavigation.QWidget.AddAction(ui.actionGo_to_page)
	ui.menuBookmarks = qt.NewQMenu(ui.menubar.QWidget)
	menuBookmarks__objectName := qt.NewQAnyStringView3("menuBookmarks")
	ui.menuBookmarks.SetObjectName(*menuBookmarks__objectName)
	menuBookmarks__objectName.Delete() // setter copied value
	ui.menuBookmarks.QWidget.AddAction(ui.actionAdd_bookmark)
	ui.menuBookmarks.AddSeparator()
	ui.menuHelp = qt.NewQMenu(ui.menubar.QWidget)
	menuHelp__objectName := qt.NewQAnyStringView3("menuHelp")
	ui.menuHelp.SetObjectName(*menuHelp__objectName)
	menuHelp__objectName.Delete() // setter copied value
	ui.menuHelp.QWidget.AddAction(ui.actionAbout)
	ui.menubar.AddMenu(ui.menuFile)
	ui.menubar.AddMenu(ui.menu_Edit)
	ui.menubar.AddMenu(ui.menu_View)
	ui.menubar.AddMenu(ui.menuNavigation)
	ui.menubar.AddMenu(ui.menuBookmarks)
	ui.menubar.AddMenu(ui.menuHelp)
	ui.MainWindow.SetMenuBar(ui.menubar)
	ui.statusbar = qt.NewQStatusBar(ui.MainWindow.QWidget)
	statusbar__objectName := qt.NewQAnyStringView3("statusbar")
	ui.statusbar.SetObjectName(*statusbar__objectName)
	statusbar__objectName.Delete() // setter copied value
	ui.MainWindow.SetStatusBar(ui.statusbar)
	ui.toolBar = qt.NewQToolBar(ui.MainWindow.QWidget)
	toolBar__objectName := qt.NewQAnyStringView3("toolBar")
	ui.toolBar.SetObjectName(*toolBar__objectName)
	toolBar__objectName.Delete() // setter copied value
	ui.toolBar.SetMovable(false)
	ui.toolBar.SetFloatable(false)
	ui.MainWindow.AddToolBar(qt.TopToolBarArea, ui.toolBar)
	/* miqt-uic: no handler for toolBar attribute 'toolBarBreak' */
	ui.toolBar.QWidget.AddAction(ui.actionFirst_page)
	ui.toolBar.QWidget.AddAction(ui.actionSkip_backward)
	ui.toolBar.QWidget.AddAction(ui.actionPrevious_page)
	ui.toolBar.QWidget.AddAction(ui.actionNext_page)
	ui.toolBar.QWidget.AddAction(ui.actionSkip_forward)
	ui.toolBar.QWidget.AddAction(ui.actionLast_page)
	ui.toolBar.AddSeparator()
	ui.toolBar.QWidget.AddAction(ui.actionPrevious_archive)
	ui.toolBar.QWidget.AddAction(ui.actionNext_archive)
	ui.toolBar.AddSeparator()
	ui.toolBar.QWidget.AddAction(ui.actionPrevious_Scene)
	ui.toolBar.QWidget.AddAction(ui.actionNext_scene)

	ui.Retranslate()

	return ui
}

// Retranslate reapplies all text translations.
func (ui *MainWindowUi) Retranslate() {
	ui.MainWindow.SetWindowTitle(qt.QCoreApplication_Tr("Gomics"))
	ui.actionOpen.SetText(qt.QMainWindow_Tr("&Open"))
	ui.actionOpen.SetShortcut(qt.NewQKeySequence2(qt.QMainWindow_Tr("Ctrl+O")))
	ui.action_no_recent_items.SetText(qt.QMainWindow_Tr("No items found"))
	ui.actionClose.SetText(qt.QMainWindow_Tr("&Close"))
	ui.actionClose.SetShortcut(qt.NewQKeySequence2(qt.QMainWindow_Tr("Ctrl+C")))
	ui.actionSave_Image.SetText(qt.QMainWindow_Tr("&Save Image"))
	ui.actionSave_Image.SetShortcut(qt.NewQKeySequence2(qt.QMainWindow_Tr("Ctrl+S")))
	ui.action_Quit.SetText(qt.QMainWindow_Tr("&Quit"))
	ui.action_Quit.SetShortcut(qt.NewQKeySequence2(qt.QMainWindow_Tr("Ctrl+Q")))
	ui.action_Preferences.SetText(qt.QMainWindow_Tr("&Preferences"))
	ui.action_Preferences.SetShortcut(qt.NewQKeySequence2(qt.QMainWindow_Tr("Ctrl+P")))
	ui.actionShrink_large_images.SetText(qt.QMainWindow_Tr("Shrink large images"))
	ui.actionShrink_large_images.SetShortcut(qt.NewQKeySequence2(qt.QMainWindow_Tr("S")))
	ui.actionEnlarge_small_images.SetText(qt.QMainWindow_Tr("Enlarge small images"))
	ui.actionEnlarge_small_images.SetShortcut(qt.NewQKeySequence2(qt.QMainWindow_Tr("E")))
	ui.actionBest_fit.SetText(qt.QMainWindow_Tr("Best fit"))
	ui.actionBest_fit.SetShortcut(qt.NewQKeySequence2(qt.QMainWindow_Tr("B")))
	ui.actionZoom_25.SetText(qt.QMainWindow_Tr("25%"))
	ui.actionZoom_33.SetText(qt.QMainWindow_Tr("33%"))
	ui.actionZoom_50.SetText(qt.QMainWindow_Tr("50%"))
	ui.actionZoom_66.SetText(qt.QMainWindow_Tr("66%"))
	ui.actionZoom_75.SetText(qt.QMainWindow_Tr("75%"))
	ui.actionZoom_100.SetText(qt.QMainWindow_Tr("100%"))
	ui.actionZoom_100.SetShortcut(qt.NewQKeySequence2(qt.QMainWindow_Tr("O")))
	ui.actionZoom_125.SetText(qt.QMainWindow_Tr("125%"))
	ui.actionZoom_150.SetText(qt.QMainWindow_Tr("150%"))
	ui.actionZoom_200.SetText(qt.QMainWindow_Tr("200%"))
	ui.actionZoom_300.SetText(qt.QMainWindow_Tr("300%"))
	ui.actionZoom_400.SetText(qt.QMainWindow_Tr("400%"))
	ui.actionZoom_800.SetText(qt.QMainWindow_Tr("800%"))
	ui.actionRotate_0.SetText(qt.QMainWindow_Tr("0°"))
	ui.actionRotate_90.SetText(qt.QMainWindow_Tr("90°"))
	ui.actionRotate_180.SetText(qt.QMainWindow_Tr("180°"))
	ui.actionRotate_270.SetText(qt.QMainWindow_Tr("270°"))
	ui.actionFit_to_width.SetText(qt.QMainWindow_Tr("Fit to width"))
	ui.actionFit_to_width.SetShortcut(qt.NewQKeySequence2(qt.QMainWindow_Tr("W")))
	ui.actionFit_to_height.SetText(qt.QMainWindow_Tr("Fit to height"))
	ui.actionFit_to_height.SetShortcut(qt.NewQKeySequence2(qt.QMainWindow_Tr("H")))
	ui.actionFullscreen.SetText(qt.QMainWindow_Tr("Fullscreen"))
	ui.actionFullscreen.SetShortcut(qt.NewQKeySequence2(qt.QMainWindow_Tr("F")))
	ui.actionSeamless_mode.SetText(qt.QMainWindow_Tr("Seamless mode"))
	ui.actionRandom_ordering.SetText(qt.QMainWindow_Tr("Random ordering"))
	ui.actionRandom_ordering.SetShortcut(qt.NewQKeySequence2(qt.QMainWindow_Tr("Ctrl+R")))
	ui.actionV_flip.SetText(qt.QMainWindow_Tr("Vertical Flip"))
	ui.actionV_flip.SetShortcut(qt.NewQKeySequence2(qt.QMainWindow_Tr("V")))
	ui.actionH_flip.SetText(qt.QMainWindow_Tr("Horizontal Flip"))
	ui.actionH_flip.SetShortcut(qt.NewQKeySequence2(qt.QMainWindow_Tr("Ctrl+V")))
	ui.actionManga_mode.SetText(qt.QMainWindow_Tr("Manga mode"))
	ui.actionManga_mode.SetShortcut(qt.NewQKeySequence2(qt.QMainWindow_Tr("M")))
	ui.actionDouble_page.SetText(qt.QMainWindow_Tr("Double page"))
	ui.actionDouble_page.SetShortcut(qt.NewQKeySequence2(qt.QMainWindow_Tr("D")))
	ui.actionPrevious_page.SetText(qt.QMainWindow_Tr("Previous page"))
	ui.actionPrevious_page.SetShortcut(qt.NewQKeySequence2(qt.QMainWindow_Tr("PgUp")))
	ui.actionNext_page.SetText(qt.QMainWindow_Tr("Next page"))
	ui.actionNext_page.SetShortcut(qt.NewQKeySequence2(qt.QMainWindow_Tr("PgDown")))
	ui.actionSkip_forward.SetText(qt.QMainWindow_Tr("Skip forward"))
	ui.actionSkip_backward.SetText(qt.QMainWindow_Tr("Skip backward"))
	ui.actionFirst_page.SetText(qt.QMainWindow_Tr("First page"))
	ui.actionFirst_page.SetShortcut(qt.NewQKeySequence2(qt.QMainWindow_Tr("Home")))
	ui.actionLast_page.SetText(qt.QMainWindow_Tr("Last page"))
	ui.actionLast_page.SetShortcut(qt.NewQKeySequence2(qt.QMainWindow_Tr("End")))
	ui.actionPrevious_archive.SetText(qt.QMainWindow_Tr("Previous archive"))
	ui.actionNext_archive.SetText(qt.QMainWindow_Tr("Next archive"))
	ui.actionGo_to_page.SetText(qt.QMainWindow_Tr("Go to page"))
	ui.actionGo_to_page.SetShortcut(qt.NewQKeySequence2(qt.QMainWindow_Tr("G")))
	ui.actionAdd_bookmark.SetText(qt.QMainWindow_Tr("Add bookmark"))
	ui.actionAdd_bookmark.SetShortcut(qt.NewQKeySequence2(qt.QMainWindow_Tr("Ctrl+B")))
	ui.actionAbout.SetText(qt.QMainWindow_Tr("About"))
	ui.actionAbout.SetShortcut(qt.NewQKeySequence2(qt.QMainWindow_Tr("F1")))
	ui.actionPrevious_Scene.SetText(qt.QMainWindow_Tr("Previous Scene"))
	ui.actionNext_scene.SetText(qt.QMainWindow_Tr("Next scene"))
	ui.menuFile.SetTitle(qt.QMenuBar_Tr("File"))
	ui.menu_Recent_Files.SetTitle(qt.QMenu_Tr("&Recent Files"))
	ui.menu_Edit.SetTitle(qt.QMenuBar_Tr("&Edit"))
	ui.menu_View.SetTitle(qt.QMenuBar_Tr("&View"))
	ui.menu_Zoom.SetTitle(qt.QMenu_Tr("Zoom"))
	ui.menu_Rotate.SetTitle(qt.QMenu_Tr("Rotate"))
	ui.menuNavigation.SetTitle(qt.QMenuBar_Tr("Navigation"))
	ui.menuBookmarks.SetTitle(qt.QMenuBar_Tr("Bookmarks"))
	ui.menuHelp.SetTitle(qt.QMenuBar_Tr("Help"))
	ui.toolBar.SetWindowTitle(qt.QMainWindow_Tr("toolBar"))
}
