// Generated by miqt-uic. To update this file, edit the .ui file in
// Qt Designer, and then run 'go generate'.
//
//go:generate miqt-uic -InFile /home/salviati/go/src/github.com/salviati/gomics/preferences.ui -OutFile /home/salviati/go/src/github.com/salviati/gomics/preferences_ui.go -Qt6 -Package main

package main

import (
	qt "github.com/mappu/miqt/qt6"
)

type PreferencesDialogUi struct {
	PreferencesDialog              *qt.QDialog
	verticalLayout                 *qt.QVBoxLayout
	tabWidget                      *qt.QTabWidget
	PreferencesAppearanceTab       *qt.QWidget
	verticalLayout_4               *qt.QVBoxLayout
	horizontalLayout_3             *qt.QHBoxLayout
	BackgroundColorButton          *qt.QPushButton
	UseBackgroundColorCheckButton  *qt.QCheckBox
	verticalSpacer_3               *qt.QSpacerItem
	PreferencesBehaviorTab         *qt.QWidget
	verticalLayout_3               *qt.QVBoxLayout
	horizontalLayout               *qt.QHBoxLayout
	PagesToSkipLabel               *qt.QLabel
	PagesToSkipSpinButton          *qt.QSpinBox
	horizontalLayout_2             *qt.QHBoxLayout
	InterpolationLabel             *qt.QLabel
	InterpolationComboBoxText      *qt.QComboBox
	verticalSpacer_2               *qt.QSpacerItem
	PreferencesDisplayTab          *qt.QWidget
	verticalLayout_2               *qt.QVBoxLayout
	OneWideCheckButton             *qt.QCheckBox
	SingleCoverCheckButton         *qt.QCheckBox
	EmbeddedOrientationCheckButton *qt.QCheckBox
	SmartScrollCheckButton         *qt.QCheckBox
	HideIdleCursorCheckButton      *qt.QCheckBox
	verticalSpacer                 *qt.QSpacerItem
	buttonBox                      *qt.QDialogButtonBox
}

// NewPreferencesDialogUi creates all Qt widget classes for PreferencesDialog.
func NewPreferencesDialogUi() *PreferencesDialogUi {
	ui := &PreferencesDialogUi{}
	ui.PreferencesDialog = qt.NewQDialog(nil)
	PreferencesDialog__objectName := qt.NewQAnyStringView3("PreferencesDialog")
	ui.PreferencesDialog.SetObjectName(*PreferencesDialog__objectName)
	PreferencesDialog__objectName.Delete() // setter copied value
	ui.PreferencesDialog.Resize(398, 282)
	ui.verticalLayout = qt.NewQVBoxLayout(ui.PreferencesDialog.QWidget)
	verticalLayout__objectName := qt.NewQAnyStringView3("verticalLayout")
	ui.verticalLayout.SetObjectName(*verticalLayout__objectName)
	verticalLayout__objectName.Delete() // setter copied value
	ui.verticalLayout.SetContentsMargins(11, 11, 11, 11)
	ui.verticalLayout.SetSpacing(6)
	ui.tabWidget = qt.NewQTabWidget(ui.PreferencesDialog.QWidget)
	tabWidget__objectName := qt.NewQAnyStringView3("tabWidget")
	ui.tabWidget.SetObjectName(*tabWidget__objectName)
	tabWidget__objectName.Delete() // setter copied value
	tabWidget__sizePolicy := qt.NewQSizePolicy()
	tabWidget__sizePolicy.SetHorizontalPolicy(qt.QSizePolicy__Expanding)
	tabWidget__sizePolicy.SetVerticalPolicy(qt.QSizePolicy__Expanding)
	tabWidget__sizePolicy.SetHorizontalStretch(0)
	tabWidget__sizePolicy.SetVerticalStretch(0)
	tabWidget__sizePolicy.SetHeightForWidth(ui.tabWidget.SizePolicy().HasHeightForWidth())
	ui.tabWidget.SetSizePolicy(*tabWidget__sizePolicy)
	tabWidget__sizePolicy.Delete() // setter copies values
	ui.PreferencesAppearanceTab = qt.NewQWidget(ui.tabWidget.QWidget)
	PreferencesAppearanceTab__objectName := qt.NewQAnyStringView3("PreferencesAppearanceTab")
	ui.PreferencesAppearanceTab.SetObjectName(*PreferencesAppearanceTab__objectName)
	PreferencesAppearanceTab__objectName.Delete() // setter copied value
	ui.verticalLayout_4 = qt.NewQVBoxLayout(ui.PreferencesAppearanceTab)
	verticalLayout_4__objectName := qt.NewQAnyStringView3("verticalLayout_4")
	ui.verticalLayout_4.SetObjectName(*verticalLayout_4__objectName)
	verticalLayout_4__objectName.Delete() // setter copied value
	ui.verticalLayout_4.SetContentsMargins(11, 11, 11, 11)
	ui.verticalLayout_4.SetSpacing(6)
	ui.horizontalLayout_3 = qt.NewQHBoxLayout2()
	horizontalLayout_3__objectName := qt.NewQAnyStringView3("horizontalLayout_3")
	ui.horizontalLayout_3.SetObjectName(*horizontalLayout_3__objectName)
	horizontalLayout_3__objectName.Delete() // setter copied value
	ui.horizontalLayout_3.SetContentsMargins(0, 0, 0, 0)
	ui.horizontalLayout_3.SetSpacing(6)
	ui.BackgroundColorButton = qt.NewQPushButton(ui.PreferencesAppearanceTab)
	BackgroundColorButton__objectName := qt.NewQAnyStringView3("BackgroundColorButton")
	ui.BackgroundColorButton.SetObjectName(*BackgroundColorButton__objectName)
	BackgroundColorButton__objectName.Delete() // setter copied value
	BackgroundColorButton__sizePolicy := qt.NewQSizePolicy()
	BackgroundColorButton__sizePolicy.SetHorizontalPolicy(qt.QSizePolicy__Fixed)
	BackgroundColorButton__sizePolicy.SetVerticalPolicy(qt.QSizePolicy__Fixed)
	BackgroundColorButton__sizePolicy.SetHorizontalStretch(0)
	BackgroundColorButton__sizePolicy.SetVerticalStretch(0)
	BackgroundColorButton__sizePolicy.SetHeightForWidth(ui.BackgroundColorButton.SizePolicy().HasHeightForWidth())
	ui.BackgroundColorButton.SetSizePolicy(*BackgroundColorButton__sizePolicy)
	BackgroundColorButton__sizePolicy.Delete() // setter copies values

	ui.horizontalLayout_3.AddWidget(ui.BackgroundColorButton.QWidget)
	ui.UseBackgroundColorCheckButton = qt.NewQCheckBox(ui.PreferencesAppearanceTab)
	UseBackgroundColorCheckButton__objectName := qt.NewQAnyStringView3("UseBackgroundColorCheckButton")
	ui.UseBackgroundColorCheckButton.SetObjectName(*UseBackgroundColorCheckButton__objectName)
	UseBackgroundColorCheckButton__objectName.Delete() // setter copied value

	ui.horizontalLayout_3.AddWidget(ui.UseBackgroundColorCheckButton.QWidget)

	ui.verticalLayout_4.AddLayout(ui.horizontalLayout_3.QLayout)
	ui.verticalSpacer_3 = qt.NewQSpacerItem4(20, 40, qt.QSizePolicy__Minimum, qt.QSizePolicy__Expanding)

	ui.verticalLayout_4.AddItem(ui.verticalSpacer_3.QLayoutItem)
	ui.tabWidget.AddTab(ui.PreferencesAppearanceTab, "")
	ui.PreferencesBehaviorTab = qt.NewQWidget(ui.tabWidget.QWidget)
	PreferencesBehaviorTab__objectName := qt.NewQAnyStringView3("PreferencesBehaviorTab")
	ui.PreferencesBehaviorTab.SetObjectName(*PreferencesBehaviorTab__objectName)
	PreferencesBehaviorTab__objectName.Delete() // setter copied value
	ui.verticalLayout_3 = qt.NewQVBoxLayout(ui.PreferencesBehaviorTab)
	verticalLayout_3__objectName := qt.NewQAnyStringView3("verticalLayout_3")
	ui.verticalLayout_3.SetObjectName(*verticalLayout_3__objectName)
	verticalLayout_3__objectName.Delete() // setter copied value
	ui.verticalLayout_3.SetContentsMargins(11, 11, 11, 11)
	ui.verticalLayout_3.SetSpacing(6)
	ui.horizontalLayout = qt.NewQHBoxLayout2()
	horizontalLayout__objectName := qt.NewQAnyStringView3("horizontalLayout")
	ui.horizontalLayout.SetObjectName(*horizontalLayout__objectName)
	horizontalLayout__objectName.Delete() // setter copied value
	ui.horizontalLayout.SetContentsMargins(0, 0, 0, 0)
	ui.horizontalLayout.SetSpacing(6)
	ui.PagesToSkipLabel = qt.NewQLabel(ui.PreferencesBehaviorTab)
	PagesToSkipLabel__objectName := qt.NewQAnyStringView3("PagesToSkipLabel")
	ui.PagesToSkipLabel.SetObjectName(*PagesToSkipLabel__objectName)
	PagesToSkipLabel__objectName.Delete() // setter copied value

	ui.horizontalLayout.AddWidget(ui.PagesToSkipLabel.QWidget)
	ui.PagesToSkipSpinButton = qt.NewQSpinBox(ui.PreferencesBehaviorTab)
	PagesToSkipSpinButton__objectName := qt.NewQAnyStringView3("PagesToSkipSpinButton")
	ui.PagesToSkipSpinButton.SetObjectName(*PagesToSkipSpinButton__objectName)
	PagesToSkipSpinButton__objectName.Delete() // setter copied value
	PagesToSkipSpinButton__sizePolicy := qt.NewQSizePolicy()
	PagesToSkipSpinButton__sizePolicy.SetHorizontalPolicy(qt.QSizePolicy__Fixed)
	PagesToSkipSpinButton__sizePolicy.SetVerticalPolicy(qt.QSizePolicy__Fixed)
	PagesToSkipSpinButton__sizePolicy.SetHorizontalStretch(0)
	PagesToSkipSpinButton__sizePolicy.SetVerticalStretch(0)
	PagesToSkipSpinButton__sizePolicy.SetHeightForWidth(ui.PagesToSkipSpinButton.SizePolicy().HasHeightForWidth())
	ui.PagesToSkipSpinButton.SetSizePolicy(*PagesToSkipSpinButton__sizePolicy)
	PagesToSkipSpinButton__sizePolicy.Delete() // setter copies values

	ui.horizontalLayout.AddWidget(ui.PagesToSkipSpinButton.QWidget)

	ui.verticalLayout_3.AddLayout(ui.horizontalLayout.QLayout)
	ui.horizontalLayout_2 = qt.NewQHBoxLayout2()
	horizontalLayout_2__objectName := qt.NewQAnyStringView3("horizontalLayout_2")
	ui.horizontalLayout_2.SetObjectName(*horizontalLayout_2__objectName)
	horizontalLayout_2__objectName.Delete() // setter copied value
	ui.horizontalLayout_2.SetContentsMargins(0, 0, 0, 0)
	ui.horizontalLayout_2.SetSpacing(6)
	ui.InterpolationLabel = qt.NewQLabel(ui.PreferencesBehaviorTab)
	InterpolationLabel__objectName := qt.NewQAnyStringView3("InterpolationLabel")
	ui.InterpolationLabel.SetObjectName(*InterpolationLabel__objectName)
	InterpolationLabel__objectName.Delete() // setter copied value

	ui.horizontalLayout_2.AddWidget(ui.InterpolationLabel.QWidget)
	ui.InterpolationComboBoxText = qt.NewQComboBox(ui.PreferencesBehaviorTab)
	InterpolationComboBoxText__objectName := qt.NewQAnyStringView3("InterpolationComboBoxText")
	ui.InterpolationComboBoxText.SetObjectName(*InterpolationComboBoxText__objectName)
	InterpolationComboBoxText__objectName.Delete() // setter copied value
	InterpolationComboBoxText__sizePolicy := qt.NewQSizePolicy()
	InterpolationComboBoxText__sizePolicy.SetHorizontalPolicy(qt.QSizePolicy__Fixed)
	InterpolationComboBoxText__sizePolicy.SetVerticalPolicy(qt.QSizePolicy__Fixed)
	InterpolationComboBoxText__sizePolicy.SetHorizontalStretch(0)
	InterpolationComboBoxText__sizePolicy.SetVerticalStretch(0)
	InterpolationComboBoxText__sizePolicy.SetHeightForWidth(ui.InterpolationComboBoxText.SizePolicy().HasHeightForWidth())
	ui.InterpolationComboBoxText.SetSizePolicy(*InterpolationComboBoxText__sizePolicy)
	InterpolationComboBoxText__sizePolicy.Delete() // setter copies values
	ui.InterpolationComboBoxText.AddItem("")
	ui.InterpolationComboBoxText.AddItem("")

	ui.horizontalLayout_2.AddWidget(ui.InterpolationComboBoxText.QWidget)

	ui.verticalLayout_3.AddLayout(ui.horizontalLayout_2.QLayout)
	ui.verticalSpacer_2 = qt.NewQSpacerItem4(20, 40, qt.QSizePolicy__Minimum, qt.QSizePolicy__Expanding)

	ui.verticalLayout_3.AddItem(ui.verticalSpacer_2.QLayoutItem)
	ui.tabWidget.AddTab(ui.PreferencesBehaviorTab, "")
	ui.PreferencesDisplayTab = qt.NewQWidget(ui.tabWidget.QWidget)
	PreferencesDisplayTab__objectName := qt.NewQAnyStringView3("PreferencesDisplayTab")
	ui.PreferencesDisplayTab.SetObjectName(*PreferencesDisplayTab__objectName)
	PreferencesDisplayTab__objectName.Delete() // setter copied value
	PreferencesDisplayTab__sizePolicy := qt.NewQSizePolicy()
	PreferencesDisplayTab__sizePolicy.SetHorizontalPolicy(qt.QSizePolicy__Preferred)
	PreferencesDisplayTab__sizePolicy.SetVerticalPolicy(qt.QSizePolicy__Preferred)
	PreferencesDisplayTab__sizePolicy.SetHorizontalStretch(0)
	PreferencesDisplayTab__sizePolicy.SetVerticalStretch(0)
	PreferencesDisplayTab__sizePolicy.SetHeightForWidth(ui.PreferencesDisplayTab.SizePolicy().HasHeightForWidth())
	ui.PreferencesDisplayTab.SetSizePolicy(*PreferencesDisplayTab__sizePolicy)
	PreferencesDisplayTab__sizePolicy.Delete() // setter copies values
	ui.verticalLayout_2 = qt.NewQVBoxLayout(ui.PreferencesDisplayTab)
	verticalLayout_2__objectName := qt.NewQAnyStringView3("verticalLayout_2")
	ui.verticalLayout_2.SetObjectName(*verticalLayout_2__objectName)
	verticalLayout_2__objectName.Delete() // setter copied value
	ui.verticalLayout_2.SetContentsMargins(11, 11, 11, 11)
	ui.verticalLayout_2.SetSpacing(6)
	ui.OneWideCheckButton = qt.NewQCheckBox(ui.PreferencesDisplayTab)
	OneWideCheckButton__objectName := qt.NewQAnyStringView3("OneWideCheckButton")
	ui.OneWideCheckButton.SetObjectName(*OneWideCheckButton__objectName)
	OneWideCheckButton__objectName.Delete() // setter copied value

	ui.verticalLayout_2.AddWidget(ui.OneWideCheckButton.QWidget)
	ui.SingleCoverCheckButton = qt.NewQCheckBox(ui.PreferencesDisplayTab)
	SingleCoverCheckButton__objectName := qt.NewQAnyStringView3("SingleCoverCheckButton")
	ui.SingleCoverCheckButton.SetObjectName(*SingleCoverCheckButton__objectName)
	SingleCoverCheckButton__objectName.Delete() // setter copied value

	ui.verticalLayout_2.AddWidget(ui.SingleCoverCheckButton.QWidget)
	ui.EmbeddedOrientationCheckButton = qt.NewQCheckBox(ui.PreferencesDisplayTab)
	EmbeddedOrientationCheckButton__objectName := qt.NewQAnyStringView3("EmbeddedOrientationCheckButton")
	ui.EmbeddedOrientationCheckButton.SetObjectName(*EmbeddedOrientationCheckButton__objectName)
	EmbeddedOrientationCheckButton__objectName.Delete() // setter copied value

	ui.verticalLayout_2.AddWidget(ui.EmbeddedOrientationCheckButton.QWidget)
	ui.SmartScrollCheckButton = qt.NewQCheckBox(ui.PreferencesDisplayTab)
	SmartScrollCheckButton__objectName := qt.NewQAnyStringView3("SmartScrollCheckButton")
	ui.SmartScrollCheckButton.SetObjectName(*SmartScrollCheckButton__objectName)
	SmartScrollCheckButton__objectName.Delete() // setter copied value

	ui.verticalLayout_2.AddWidget(ui.SmartScrollCheckButton.QWidget)
	ui.HideIdleCursorCheckButton = qt.NewQCheckBox(ui.PreferencesDisplayTab)
	HideIdleCursorCheckButton__objectName := qt.NewQAnyStringView3("HideIdleCursorCheckButton")
	ui.HideIdleCursorCheckButton.SetObjectName(*HideIdleCursorCheckButton__objectName)
	HideIdleCursorCheckButton__objectName.Delete() // setter copied value

	ui.verticalLayout_2.AddWidget(ui.HideIdleCursorCheckButton.QWidget)
	ui.verticalSpacer = qt.NewQSpacerItem4(20, 40, qt.QSizePolicy__Minimum, qt.QSizePolicy__Expanding)

	ui.verticalLayout_2.AddItem(ui.verticalSpacer.QLayoutItem)
	ui.tabWidget.AddTab(ui.PreferencesDisplayTab, "")

	ui.verticalLayout.AddWidget(ui.tabWidget.QWidget)
	ui.buttonBox = qt.NewQDialogButtonBox(ui.PreferencesDialog.QWidget)
	buttonBox__objectName := qt.NewQAnyStringView3("buttonBox")
	ui.buttonBox.SetObjectName(*buttonBox__objectName)
	buttonBox__objectName.Delete() // setter copied value
	ui.buttonBox.SetOrientation(qt.Horizontal)
	ui.buttonBox.SetStandardButtons(qt.QDialogButtonBox__Cancel | qt.QDialogButtonBox__Ok)

	ui.verticalLayout.AddWidget(ui.buttonBox.QWidget)

	ui.buttonBox.OnAccepted(ui.PreferencesDialog.Accept)
	ui.buttonBox.OnRejected(ui.PreferencesDialog.Reject)

	ui.Retranslate()

	ui.tabWidget.SetCurrentIndex(2)

	return ui
}

// Retranslate reapplies all text translations.
func (ui *PreferencesDialogUi) Retranslate() {
	ui.PreferencesDialog.SetWindowTitle(qt.QCoreApplication_Tr("Preferences"))
	ui.tabWidget.SetTabText(ui.tabWidget.IndexOf(ui.PreferencesAppearanceTab), qt.QTabWidget_Tr("Appearance"))
	ui.UseBackgroundColorCheckButton.SetText(qt.QWidget_Tr("Use custom background color"))
	ui.tabWidget.SetTabText(ui.tabWidget.IndexOf(ui.PreferencesBehaviorTab), qt.QTabWidget_Tr("Behavior"))
	ui.PagesToSkipLabel.SetText(qt.QWidget_Tr("Number of pages to skip: "))
	ui.InterpolationLabel.SetText(qt.QWidget_Tr("Image interpolation algorithm:"))
	ui.InterpolationComboBoxText.SetItemText(0, qt.QComboBox_Tr("Nearest"))
	ui.InterpolationComboBoxText.SetItemText(1, qt.QComboBox_Tr("Bilinear"))
	ui.tabWidget.SetTabText(ui.tabWidget.IndexOf(ui.PreferencesDisplayTab), qt.QTabWidget_Tr("Display"))
	ui.OneWideCheckButton.SetText(qt.QWidget_Tr("Display one wide image in double-page mode"))
	ui.SingleCoverCheckButton.SetText(qt.QWidget_Tr("Display cover as single page"))
	ui.EmbeddedOrientationCheckButton.SetText(qt.QWidget_Tr("Automatically rotate images according to EXIF data"))
	ui.SmartScrollCheckButton.SetText(qt.QWidget_Tr("Use smart scroll"))
	ui.HideIdleCursorCheckButton.SetText(qt.QWidget_Tr("Hide the cursor while stationary"))
}
